### PR TITLE
Nanoseconds (but less years)

### PR DESCRIPTION
**Pull request by arnwas**
Your "smalltime" helped me solving a nice problem here (store lots of timestamps in condensed form), but i needed nanoseconds as well.
Maybe this is interesting for you as well, or others of your users?

Cheers, Arno

### CODE REVIEW

**Comment by kstenerud** [comment]
Hey that's cool. Actually, years prior to, say, 1800 or so, aren't really that important tbh... Maybe a different zero year is a good idea. I need to think on this a bit...

**Comment by kstenerud** [comment]
With only 256 years to play with, we'd have to think carefully about what to choose as the zero year. Ideally, you'd want a zero year where it's highly unlikely that anyone would want a nanosecond precision time prior to that date.

At what year did nanoseconds actually become important? Unix epoch is 1970... Are there likely to be any nanosecond timestamps before then? With 1970 as a zero year, you'd have valid dates until 2226...

**Comment by arnwas** [comment]
Yes, I also thought about 1970 being a better choice. Sounds reasonable.

**Comment by kstenerud** [comment]
OK, I'll update it to 1970. Thanks for this :)

**Pull request merged**
